"use client";
import { useState } from "react";
import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Arthur's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
  };

  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${robotoMono.variable} antialiased bg-gradient-to-b from-blue-500 to-black min-h-screen text-white`}
      >
        <header className="flex flex-col sm:flex-row justify-between items-center p-4 bg-opacity-75 bg-black">
          <h1 className="text-2xl font-bold hover:text-blue-300 transition duration-300">
            Arthur
          </h1>
          <button
            className="sm:hidden text-2xl focus:outline-none"
            onClick={toggleMenu}
          >
            &#9776;
          </button>
          <nav className="hidden sm:flex space-x-4 mt-4 sm:mt-0 sm: text-left">
            <a
              href="#about"
              className="hover:text-blue-300 transition duration-300 transform hover:scale-110"
            >
              Sobre mí
            </a>
            <a
              href="#projects"
              className="hover:text-blue-300 transition duration-300 transform hover:scale-110"
            >
              Proyectos
            </a>
            <a
              href="#contact"
              className="hover:text-blue-300 transition duration-300 transform hover:scale-110"
            >
              Contáctame
            </a>
          </nav>
          <div className="hidden sm:flex space-x-4 mt-4 sm:mt-0">
            <button className="hover:text-blue-300 transition duration-300">
              EN/ES
            </button>
            <button className="hover:text-blue-300 transition duration-300">
              🌞/🌜
            </button>
          </div>
        </header>
        {isMenuOpen && (
          <aside className="fixed inset-0 bg-black bg-opacity-75 flex flex-col items-center justify-center z-50">
            <button
              className="text-4xl text-white mb-8 focus:outline-none"
              onClick={toggleMenu}
            >
              &times;
            </button>
            <nav className="flex flex-col space-y-4 text-2xl">
              <a
                href="#about"
                className="hover:text-blue-300 transition duration-300"
                onClick={toggleMenu}
              >
                Sobre mí
              </a>
              <a
                href="#projects"
                className="hover:text-blue-300 transition duration-300"
                onClick={toggleMenu}
              >
                Proyectos
              </a>
              <a
                href="#contact"
                className="hover:text-blue-300 transition duration-300"
                onClick={toggleMenu}
              >
                Contáctame
              </a>
              <button
                className="hover:text-blue-300 transition duration-300"
                onClick={toggleMenu}
              >
                EN/ES
              </button>
              <button
                className="hover:text-blue-300 transition duration-300"
                onClick={toggleMenu}
              >
                🌞/🌜
              </button>
            </nav>
          </aside>
        )}
        <main className="flex-grow p-4 sm:p-8">{children}</main>
        <footer className="p-4 bg-opacity-75 bg-black text-center">
          <p>&copy; {new Date().getFullYear()} Hecho por Arthur</p>
        </footer>
      </body>
    </html>
  );
}
